version: '3.9'

services: 
    zoo1:
        image: bitnami/zookeeper:3.7.0
        restart: always
        hostname: zoo1
        container_name: zoo1
        ports:
            - 2184:2181
        volumes: 
            - "/home/jphao/kafka/zkcluster/zoo1:/bitnami/zookeeper"
        environment: 
            ZOO_SERVER_ID: 1
            ZOO_SERVERS: 0.0.0.0:2888:3888, zoo2:2888:3888, zoo3:2888:3888
            ALLOW_ANONYMOUS_LOGIN: 'true'
        networks:
            kafka:
                ipv4_address: 172.30.0.11

    zoo2:
        image: bitnami/zookeeper:3.7.0
        restart: always
        hostname: zoo2
        container_name: zoo2
        ports:
            - 2185:2181
        volumes: 
            - "/home/jphao/kafka/zkcluster/zoo2:/bitnami/zookeeper"
        environment: 
            ZOO_SERVER_ID: 2
            ZOO_SERVERS: zoo1:2888:3888, 0.0.0.0:2888:3888, zoo3:2888:3888
            ALLOW_ANONYMOUS_LOGIN: 'true'
        networks:
            kafka:
                ipv4_address: 172.30.0.12

    zoo3:
        image: bitnami/zookeeper:3.7.0
        restart: always
        hostname: zoo3
        container_name: zoo3
        ports:
            - 2186:2181
        volumes: 
            - "/home/jphao/kafka/zkcluster/zoo3:/bitnami/zookeeper"
        environment: 
            ZOO_SERVER_ID: 3
            ZOO_SERVERS: zoo1:2888:3888, zoo2:2888:3888, 0.0.0.0:2888:3888
            ALLOW_ANONYMOUS_LOGIN: 'true'
        networks:
            kafka:
                ipv4_address: 172.30.0.13

networks: 
    kafka:
        external: 
            name: kafka 