server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xiaoxin
    password: 123456
    url: jdbc:mysql://114.214.219.193:3306/mybatis_demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    hikari:
      connection-timeout: 1200
      maximum-pool-size: 20
      idle-timeout: 180000

mybatis:
  type-aliases-package: com.olivine.mybatis.entity.domain
  mapper-locations:
    - classpath:mybatis/mapper/**Mapper.xml
  configuration:
    map-underscore-to-camel-case: true