server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xiaoxin
    password: 123456
    url: jdbc:mysql://222.195.87.224:3306/mybatis_demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC

mybatis:
  type-aliases-package: com.olivine.mybatis.entity.domain
  mapper-locations:
    - classpath:mybatis/mapper/**Mapper.xml
  configuration:
    map-underscore-to-camel-case: true